# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='is_archived',
        ),
    ]
