# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_plugin', '0003_auto_20190328_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='new_author',
        ),
    ]
