# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive_plugin', '0004_remove_version_new_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.Article'),
        ),
        migrations.AlterField(
            model_name='version',
            name='base_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='submission.Article'),
        ),
        migrations.AlterField(
            model_name='version',
            name='parent_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='submission.Article'),
        ),
    ]
